config/routes.rb
Phuc::Application.routes.draw do
  get "products/index"

  get "reports/index"

  devise_for :users

  root to: "home#index"
  resources :quanly
  resources :orders
  resources :order_items
  resources :reports
  resources :products
  match '/hoa-don.php', to: 'reports#report_bill', as: 'report_bill'
  match '/update_table_status', to: 'tables#update_table_status', as: 'update_table_status'
  match '/bao-cao-doanh-thu.php', to: 'reports#report_revenue', as: 'report_revenue'
  match '/hoa-don-chi-tiet.php', to: 'reports#reports_detail', as: 'report_detail'
  match '/bao-cao-doanh-thu-theo-san-pham.php', to: 'reports#report_product', as: 'report_product'
  match '/xoa-order', to: 'orders#delete_order', as: 'delete_order'

end

app/models/quanly.rb
#encoding: utf-8
class Quanly < ActiveRecord::Base
  self.table_name = "quanly"
  attr_accessible :name, :status, :karaoke, :vip
  has_friendly_id :name, :use_slug => true
  has_many :orders
end

app/controllers/quanly_controller.rb
class QuanlyController < ApplicationController

  def show
    @table = Quanly.find(params[:id])
    if params[:product_search].present?
      @products = Product.where("name LIKE ?", "%#{params[:product_search]}%")
      session[:tab] = "tc"
    else
      @products = Product.all
    end
    @service_products = Product.where(category_id: 3)
    @da_products = Product.where(category_id: 1)
    @du_products = Product.where(category_id: 2)
    session[:table_id] = @table.id
    if current_table.orders.present? && current_table.orders.last.status == 'wait'
      @order = Order.where(quanly_id: current_table.id, status: 'wait').first
      session[:order_id] = @order.id
      @order_item = current_order.order_items.new
      @order_items = current_order.order_items
    else
      @order = current_table.orders.new
    end
    @order_new = current_table.orders.new
  end

  def create_orders
    @table = current_table
    @table.orders.new(params[:order])
    if @table.orders.save!
      @table.update_attributes(:status => 'open')
    end
  end

  def update_table_status
    @table = current_table
    order = current_order
    @table.update_attributes(:status => 'closed')
    order.update_attributes(:status => 'complete')
    if params[:save].present?
      order = Order.where(:id => current_order.id).first
      order.update_attributes(params[:order])
      redirect_to :back
    elsif params[:checkout].present?
      @table.update_attributes(:status => 'closed')
      current_order.update_attributes(:status => 'complete')
      redirect_to root_path
    end
  end
end

app/views/quanly/_product_row.html.haml
%table{width: "100%"}
  %tbody
    - product.each do |product|
      %tr{width: "100%"}
        %td{width: "50%"}
          %span{:style => "color: green"}
            %strong #{product.name}
        %td
          %span{:style => "color: red"} #{number_with_delimiter product.price}
        = form_for order_item, url: order_items_path do |f| 
          %td{width: "30%"}
            %input{type: "text", name: "order_item[quantity]", style: "width: 40px", value: 1}
            %input{type: "hidden", name: "tab", value: tab}
          %td{width: "10%"}
            %input{:name => "order_item[product_id]", value: product.id, type: "hidden"}
            = f.submit "Thêm", name: "add", style: "height: 28px"