config/routes.rb
Phuc::Application.routes.draw do
  get "products/index"

  get "reports/index"

  devise_for :users

  root to: "home#index"
  resources :quanly
  resources :orders
  resources :order_items
  resources :reports
  resources :products
  match '/hoa-don.php', to: 'reports#report_bill', as: 'report_bill'
  match '/update_table_status', to: 'tables#update_table_status', as: 'update_table_status'
  match '/bao-cao-doanh-thu.php', to: 'reports#report_revenue', as: 'report_revenue'
  match '/hoa-don-chi-tiet.php', to: 'reports#reports_detail', as: 'report_detail'
  match '/bao-cao-doanh-thu-theo-san-pham.php', to: 'reports#report_product', as: 'report_product'
  match '/xoa-order', to: 'orders#delete_order', as: 'delete_order'

end

app/views/layouts/shared/_footer.html.haml
_footer.html.haml

app/views/layouts/shared/_header.html.haml
%script{:src => "/assets/jquery.menu.js", :type => "text/javascript"}
#_header_region.simple-layout-banner
  #module_70
    .hotel-banner
      .banner-logo
        .sign-in
          %a
            = link_to current_user.name, edit_user_registration_path
          |
          = link_to "Logout", destroy_user_session_path, :method => :delete, class: "log-out"
      %div{:style => "clear:both; height:0px; font-size:0px;"}
      .clear-both
      .main-menu-bound
        %ul#main_menu.menu
          %li.menumain
            %img.img{:src => "/assets/fb.png"}>/
            Nhà hàng
            %ul{:style => "display: none;"}
              %li
                = link_to "Quản lý sản phẩm", products_path
              %li
              %li
                = link_to "Sơ đồ bàn", root_path
              %li
              %li
                Danh sách bàn Checkin
              %li
              %li
                = "Danh sách bàn Checkout"
              %li
              %li
                = link_to "Báo cáo doanh thu", report_revenue_path
              %li
              %li
                = link_to "Báo cáo doanh thu theo sản phẩm", report_product_path
              %li
              %li
                Bảng kê hàng hóa
          %li.menumain
            %img.img{:src => "/assets/system.png"}>/
            Hệ thống
            %ul{:style => "display: none;"}
              %li
                Quản lý danh sách người dùng phần mềm
              %li
              %li
                Cập nhật giá cho sản phẩm
              %li
              %li
                Báo cáo tình hình sử dụng phần mềm
            %ul{:style => "display: none;"}
        %div{:style => "clear:both; height:0px; font-size:0px;"}
    :javascript
      var options = {minWidth: 120, arrowSrc: 'packages/cms/skins/default/images/arrow_right.gif', onClick: function(e, menuItem){ window.location = jQuery(this).children('div').children('a').attr('href');}};var logo = new Image();logo.src = "/assets/banner.png";if(logo.width > screen.width-21 || 1){jQuery('.banner-logo > img').css('width',screen.width-21);}jQuery('#main_menu').menu(options);/*if (jQuery.browser.msie && jQuery.browser.version.substr(0,1)<7) {jQuery('.menumain').hover(function(){  jQuery('select').each(function(){jQuery(this).css('display','none');  });},function(){  jQuery('select').each(function(){jQuery(this).css('display','');  }); jQuery('#root-menu-div ul').hover(function(){ jQuery('select').each(function(){jQuery(this).css('display','none');  });},function(){  jQuery('select').each(function(){jQuery(this).css('display','');  });}  );});}*/
    %div{:style => "padding-top:25px;"}
      %center
        = link_to root_path do
          %img{:src => "/assets/banner.png"}/