config/routes.rb
Phuc::Application.routes.draw do
  get "products/index"

  get "reports/index"

  devise_for :users

  root to: "home#index"
  resources :quanly
  resources :orders
  resources :order_items
  resources :reports
  resources :products
  match '/hoa-don.php', to: 'reports#report_bill', as: 'report_bill'
  match '/update_table_status', to: 'tables#update_table_status', as: 'update_table_status'
  match '/bao-cao-doanh-thu.php', to: 'reports#report_revenue', as: 'report_revenue'
  match '/hoa-don-chi-tiet.php', to: 'reports#reports_detail', as: 'report_detail'
  match '/bao-cao-doanh-thu-theo-san-pham.php', to: 'reports#report_product', as: 'report_product'
  match '/xoa-order', to: 'orders#delete_order', as: 'delete_order'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :unit, :category_id, :stock_sold
  has_many :order_items
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     if params[:product_search].present?
      session[:product_search] = params[:product_search]
      @products = Product.where("products.name LIKE ?", "%#{session[:product_search]}%")
    else
      @products = Product.all
    end
  end
  
  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.create(params[:product])
    redirect_to products_path
  end

  def update
    product = Product.find(params[:id])
    product.update_attributes(params[:product])
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
#printer.simple-layout-center
  #module_472
    .product-bill-bound 
      %br
      .content
        %fieldset
          %legend.title Sản phẩm, hàng hóa
          %table
            = form_for @product do |f|
              %tbody
                %tr
                  %td{width: "50px"}
                  %td{width: "110px"}
                    = "Tên sản phâm"
                  %td
                    %input{type: "text", name: "product[name]", value: @product.name}
                %tr
                  %td
                  %td
                    = "Danh mục sản phẩm"
                  %td
                    = select_tag :product, options_for_select(@categories, :selected => @product.category_id), name: "product[category_id]"
                %tr
                  %td
                  %td
                    = "Đơn vị"
                  %td
                    %input{type: "text", name: "product[unit]", value: @product.unit}
                %tr
                  %td
                  %td
                    = "Giá"
                  %td{style: "margin-top: 50px"}
                    %input{type: "text", name: "product[price]", value: @product.price}
                %tr
                  %td
                  %td
                  %td{:align => "right"}
                    = f.submit "Cập nhật"

app/views/products/index.html.haml
#printer.simple-layout-center
  #module_472
    .product-supplier-bound
      %table.table-bound{:border => "0", :bordercolor => "#CCCCCC", :cellpadding => "15", :cellspacing => "0", :width => "100%"}
        %tbody
          %tr
            %td.form-title Cập nhật giá hàng hóa, sản phẩm
            %td{:align => "right", :nowrap => "nowrap", :width => "1%"}
              = link_to "Thêm mới sản phẩm", new_product_path
    .content
      .search-box
        %fieldset
          %legend.title Tìm kiếm
          = form_tag products_path, method: "get" do
            = text_field_tag :product_search
            = submit_tag :Search, name: nil
      %br
    %fieldset
      %table{:border => "1", :bordercolor => "#CCCCCC", :cellpadding => "3", :cellspacing => "0", :width => "100%"}
        %tbody
          %tr{:bgcolor => "#F1F1F1"}
            %th{:width => "1%"} STT
            %th{:align => "center", :width => "20%"} Sản phẩm
            %th{:align => "center", :width => "7%"} Danh mục
            %th{:align => "center", :width => "7%"} Đơn vị
            %th{:align => "center", :width => "7%"} Giá
            %th{:align => "center",:width => "5%"} Hành động
          - i = 1
          - @products.each do |t|
            %tr
              %td{:align => "center"}
                = i
                - i = i + 1
              %td{:style => "cursor:pointer;"}
                = t.name
              %td
                - category = Category.where(id: t.category_id).first
                = category.name
              %td{:style => "cursor:pointer;"}
                = t.unit
              %td{:align => "right", :style => "cursor:pointer;"}
                = number_with_delimiter t.price
              %td{:align => "center"}
                = link_to edit_product_path(t) do
                  %img{:src => "/assets/edit.gif", title: "Sua"}/
                - unless t.id == 36 || t.id == 37
                  = link_to t, method: :delete do
                    %img{:src => "/assets/delete.gif", title: "Xoa"}/
        /   %br/
        /   .paging
        /     .paging-bound
        /       %span> Trang
        /        
        /       %font{:style => "font-weight:bold;"}> 1
        /        
        /       %a{:href => "http://192.168.1.3:8081/?page=product_price&page_no=2&portal=default"}> 2
        /          
        /       %a{:href => "http://192.168.1.3:8081/?page=product_price&page_no=2&portal=default"} Trang tiếp
        / %input{:name => "act", :type => "hidden", :value => ""}/
        / %input{:name => "cmd", :type => "hidden", :value => ""}/
        / %input{:name => "form_block_id", :type => "hidden", :value => "472"}/

app/views/products/new.html.haml
#printer.simple-layout-center
  #module_472
    .product-bill-bound 
      %br
      .content
        %fieldset
          %legend.title Sản phẩm, hàng hóa
          %table
            = form_for @product do |f|
              %tbody
                %tr
                  %td{width: "50px"}
                  %td{width: "110px"}
                    = "Tên sản phâm"
                  %td
                    %input{type: "text", name: "product[name]"}
                %tr
                  %td
                  %td
                    = "Danh mục sản phẩm"
                  %td
                    = select_tag :product, options_for_select(@categories), name: "product[category_id]"
                %tr
                  %td
                  %td
                    = "Đơn vị"
                  %td
                    %input{type: "text", name: "product[unit]"}
                %tr
                  %td
                  %td
                    = "Giá"
                  %td{style: "margin-top: 50px"}
                    %input{type: "text", name: "product[price]"}
                %tr
                  %td
                  %td
                  %td{:align => "right"}
                    = f.submit "Save"