config/routes.rb
Phuc::Application.routes.draw do
  get "products/index"

  get "reports/index"

  devise_for :users

  root to: "home#index"
  resources :quanly
  resources :orders
  resources :order_items
  resources :reports
  resources :products
  match '/hoa-don.php', to: 'reports#report_bill', as: 'report_bill'
  match '/update_table_status', to: 'tables#update_table_status', as: 'update_table_status'
  match '/bao-cao-doanh-thu.php', to: 'reports#report_revenue', as: 'report_revenue'
  match '/hoa-don-chi-tiet.php', to: 'reports#reports_detail', as: 'report_detail'
  match '/bao-cao-doanh-thu-theo-san-pham.php', to: 'reports#report_product', as: 'report_product'
  match '/xoa-order', to: 'orders#delete_order', as: 'delete_order'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  def index
  end
  def report_bill
    @order = Order.find_by_id(params[:id])
    @bills = @order.order_items
  end

  def reports_detail
    @order = Order.find(params[:order_id])
    @bills = @order.order_items
  end

  def report_revenue
    if params[:start_date].present?
      session[:start_date] = params[:start_date]
      session[:to_date] = params[:to_date]
      start_date = Date.strptime(params[:start_date], "%d-%m-%Y").strftime("%Y-%m-%d")
      to_date = Date.strptime(params[:to_date], "%d-%m-%Y").strftime("%Y-%m-%d")
      if params[:bill].present?
        @orders = Order.where(:status => "complete").where("orders.created_at >= ? AND orders.created_at <= ?", start_date.to_date, to_date.to_date + 1.day)
        if @orders.empty?
          @nodata = true
        end
      elsif params[:products].present?
        @products = Product.joins(:order_items).group("order_items.product_id").
                    where("order_items.created_at >= ? AND order_items.created_at <= ?", start_date.to_date, to_date.to_date + 1.day).
                    where("stock_sold > ?", 0)
        if @products.empty?
          @nodata = true
        end
      end
    end
  end

  def report_product
    @products = Product.where("stock_sold > ?", 0)
  end

end

app/views/reports/index.html.erb
<div class="simple-layout-center" id="printer">
<div id="module_505"><style>
  <!--<!--//IF:cond($this->map['preview'])-->
  <!--@media print{body {display:none;}}-->
  <!--//IF:cond-->-->
  .restaurant-invoice-bound{
    float:left;
    width:400px;
    padding:5px;
  }
  #product_detail{
    border:1px solid #E5E6E7; 
  }
  #product_detail tr{
    border:1px solid #E5E6E7; 
  }
  #product_detail tr td{
    border:1px solid #E5E6E7; 
  }
  #product_detail tr th{
    border:1px solid #E5E6E7; 
  }
</style>
<div style="width:700px;text-align:center; margin:auto !important; border:1px solid silver; padding:5px;">
<div class="restaurant-invoice-bound">
  <div class="item-body">
  <table cellpadding="0" cellspacing="0" width="100%" style="margin-bottom:10px;">
  <tbody><tr>
  
  <td width="1%"><img src="./hóa đơn_files/logo.jpg" width="80px;"></td>
    <td style=" text-align:left; padding-left:50px;">
          <span>HOÀNG CHÂU PALACE</span><br>
            <span>Mã số thuế: 0 1 0 5 8 0 0 8 4 6 </span><br>
            <span>Địa chỉ: Tuần B - Quỳnh Châu - Quỳnh Lưu - Nghệ An</span><br>
            <span>Điện thoại: 0982 382 000</span><br>
        </td>
  
  </tr>
  <tr>
      <td></td>
      <td style=" text-align:center;"><span style="font-size:18px;font-weight:bold;">INVOICE/ HÓA ĐƠN THANH TOÁN</span><br>
      <span style="font-size:11px;">Ngày 01 Tháng 12 Năm 2014</span><br>
    </td>
    </tr>
</tbody></table>
        <table cellpadding="0" cellspacing="0" style="width: 100%; margin: 10px auto;">
            <tbody><tr>
                <td style="text-align: left; font-size: 11px;">Số hóa đơn: LP-011214-3</td>
                <td style="text-align: right; font-size: 11px;">Thu ngân/Cashier: Tamxinh</td>
            </tr>
            <tr>
                <td style="text-align: left; font-size: 11px;">Agent/Khách hàng: Mang về</td>
                <td style="text-align: right; font-size: 11px;">Ngày in: 01/12/2014 14:58'</td>
            </tr>
            <tr>
                <td style="text-align: left; font-size: 11px;">Bàn/Table No: Bàn 01 (SL Người: 1) &nbsp;</td>
            </tr>
        </tbody></table>
    </div>
  
   <div class="item-body"></div><br>
    <div style="border-bottom:1px solid #E5E6E7"></div>
        <table width="100%" cellspacing="0" border="0" bordercolor="#000000" id="product_detail">
          <tbody><tr>
                                                                   <th width="1%" align="left">STT<br>
            No </th>
            <th width="50%" align="left" style="padding-left:10px;">Diễn giải<br>
            Description </th>
             <th width="10%" align="center">Đơn vị<br>
            Unit</th>
             <th width="8%" align="center">Yêu cầu<br>
            Quantity</th>
                         <th width="8%" align="center">SD<br>
            used</th>
            <th width="10%" align="center">Đơn giá<br>Price</th>
                        <th width="20%" align="center" nowrap="nowrap">Thành tiền<br>
            Amount </th>
          </tr>
                                        <tr valign="top">
            <td>1</td>
            <td align="left"> thạch quy linh<div class="item-body"></div></td>
            <td align="center">Bát</td>
            <td align="center">4</td>
                         <td align="center">4</td>
            <td align="right">10,000</td>
                       <td align="right">40,000</td>
          </tr>
                     
                                  </tbody></table>
      <div style="border-bottom:1px solid #E5E6E7"></div>
      <div class="item-body total-group">
      <div class="item-body">&nbsp;</div>
      <table width="100%" border="0" cellspacing="0" cellpadding="2">
        <tbody><tr>
            <td align="right">
              <table width="350" cellpadding="2" border="0">
              <tbody><tr>
                <td width="80%"><strong>Thành tiền/Amount:</strong><div class="sub-item-body"></div></td>
                <td width="20%" align="right">40,000</td>
              </tr>
                            <tr>
                <td><strong>Giảm giá/Order Discount:</strong><div class="sub-item-body"></div></td>
                <td align="right"> - 0</td>
              </tr>
                             <tr>
                <td><strong>Tổng sau giảm giá:</strong><div class="sub-item-body"></div></td>
                <td align="right">40,000</td>
              </tr>
              <tr>
                <td><strong> (0%)Phí dịch vụ/Service charge: </strong><div class="sub-item-body"></div></td>
                <td align="right"> + 0</td>
              </tr>
              <tr>
                <td><strong>Tổng bao gồm phí dịch vụ:</strong><div class="sub-item-body"></div></td>
                <td align="right">40,000</td>
              </tr>
                            <tr>
                <td><strong>(10%) Thuế/Tax:</strong><div class="sub-item-body"></div></td>
                <td align="right"> + 4,000</td>
              </tr>
              <tr>
                <td><strong>Tổng bao gồm thuế:</strong><div class="sub-item-body"></div></td>
                <td align="right">44,000</td>
              </tr>
              
                                    
              <tr>
                <td nowrap="nowrap" align="left" style="border:1px solid #000;border-right:0px;"><strong>Tổng tiền thanh toán/Grant Total:</strong><div class="sub-item-body"></div></td>
                <td align="right" style="border:1px solid #000;border-left:0px;"><span style="font-size:14px;font-weight:bold;">44,000</span></td>
              </tr>
               <tr>
                <td nowrap="nowrap" align="left"><strong></strong><div class="sub-item-body"></div></td>
                <td align="right"><span style="font-size:12px;font-weight:bold;">$ 44,000</span></td>
              </tr>
                            </tbody></table>
            <div><span><i>(*) Quý khách vui lòng lấy hóa đơn GTGT trong tháng. <br>Cảm ơn Quý khách đã sử dụng dịch vụ tại Hoang Chau Palace!</i></span></div>
            <div style="color:#F00;font-weight:bold;padding-top:10px;font-size:16px;"></div>
          </td>
        </tr>
    </tbody></table>


    </div>
  </div>
</div>
</div>
</div>

app/views/reports/report_bill.html.haml
#module_505
  :css
    / <!--//IF:cond($this->map['preview'])
    / @media print{body {display:none;}}
    / //IF:cond
    \-->
    .restaurant-invoice-bound{
      float:left;
      width:400px;
      padding:5px;
    }
    #product_detail{
      border:1px solid #E5E6E7; 
    }
    #product_detail tr{
      border:1px solid #E5E6E7; 
    }
    #product_detail tr td{
      border:1px solid #E5E6E7; 
    }
    #product_detail tr th{
      border:1px solid #E5E6E7; 
    }
  %div{:style => "width:369px;text-align:center; margin:auto !important; border:1px solid silver; padding:5px; font-size: 14px"}
    .restaurant-invoice-bound
      %li.menumain{:style => "float:right;list-style-type: none;"}
        %a{:onclick => "window.print();return false;", :title => "In"}
          %img{:height => "20", :src => "/assets/printer.png"}/
        %ul{:style => "display: none;"}
      .item-body
        %table{:style => "margin-bottom:10px;font: Courier 10 Pitch", :width => "100%"}
          %tbody
            %tr
              %td{:width => "1%"}
                %img{:src => "/assets/hoa_don.png", :width => "80px;"}/
              %td{:style => " text-align:left; padding-left:10px;"}
                %span{:style => "font-size:18px;font-weight:bold;"} HOÀNG CHÂU PALACE
                %br/
                %span Địa chỉ: Tuần B - Quỳnh Châu - Quỳnh Lưu - Nghệ An
                %br/
                %span Điện thoại: 0967 938 998
                %br/
            %tr
              %td{colspan: "2", align: "left"}
                %strong
                  %i
                    %u Chuyên:
                  %p{style: "margin: auto"}
                    %span{style: "font-size:13px"}
                      = "- Nhà hàng đặc sản rừng - biển, tiệc cưới, tổ chức sự kiện"
                      %br{style: "float: left"}
                        = "- Karaoke, cafe"
            %tr
              %td{align: "center", colspan: "2"}
                %span{:style => "font-weight:bold;"} HÓA ĐƠN THANH TOÁN
                %br/
                %span
                  = DateTime.now.to_date.strftime("Ngày %d Tháng %m Năm %Y")
                %br/
                - if current_order.quanly.karaoke == true
                  %span{:style => "font-size:11px;"}
                    = "Từ #{current_order.giovao} đến #{current_order.giora}"
                  %br/
       
      .item-body
      %br/
      %div{:style => "border-bottom:1px solid #E5E6E7"}
      %table#product_detail{:width => "100%"}
        %tbody
          %tr
            %th{:align => "left", :width => "1%"}
              STT
            %th{:align => "left", :style => "padding-left:10px;", :width => "20%"}
              Diễn giải
            %th{:align => "center", :width => "15%"}
              Sử dụng
            %th{:align => "center", :width => "10%"}
              Đơn giá
            %th{:align => "center", :nowrap => "nowrap", :width => "20%"}
              Thành tiền
          - i = 1
          - @bills.each do |t|
            - product = Product.where(id: t.product_id).first
            %tr{:valign => "top"}
              %td
                = i
                - i = i + 1
              %td{:align => "left"}
                = product.name
                .item-body
              %td{:align => "right"}
                - if product.id == 36 || product.id == 37
                  - a = (t.quantity * 60 ).divmod(60)[0]
                  - b = (t.quantity * 60 ).divmod(60)[1].round
                  = "#{a} giờ #{b} '"
                - elsif t.quantity.divmod(1)[0] == t.quantity
                  = t.quantity.round
                - else
                  = t.quantity
              %td{:align => "right"}
                = number_with_delimiter product.price
              %td{:align => "right"}
                = number_with_delimiter t.total_price.round
      %div{:style => "border-bottom:1px solid #E5E6E7"}
      .item-body.total-group
        .item-body &nbsp;
        %table{:border => "0", :cellpadding => "2", :cellspacing => "0", :width => "100%"}
          %tbody
            %tr
              %td{:align => "right"}
                %table{:border => "0", :cellpadding => "2", :width => "350"}
                  %tbody
                    - if @order.tax != 0 || @order.sale_off != 0
                      %tr
                        %td{:width => "80%"}
                          %strong Thành tiền:
                          .sub-item-body
                        %td{:align => "right", :width => "20%"}
                          = number_with_delimiter @order.total_price.round
                    - if @order.sale_off != 0
                      %tr
                        %td
                          %strong Giảm giá/Order Discount:
                          .sub-item-body
                        %td{:align => "right"}
                          = "- #{number_with_delimiter (@order.total_price * @order.sale_off / 100).round}"
                      %tr
                        %td
                          %strong Tổng sau giảm giá:
                          .sub-item-body
                        %td{:align => "right"}
                          = number_with_delimiter @order.after_sale_off.round
                    - if @order.tax != 0
                      %tr
                        %td
                          %strong (10%) Thuế/Tax:
                          .sub-item-body
                        %td{:align => "right"}
                          = "+ #{number_with_delimiter (@order.after_sale_off * @order.tax / 100).round}"
                      %tr
                        %td
                          %strong Tổng bao gồm thuế:
                          .sub-item-body
                        %td{:align => "right"}
                          = number_with_delimiter @order.final_total
                    %tr
                      %td{:align => "left", :nowrap => "nowrap", :style => "border:1px solid #000;border-right:0px;"}
                        %strong Tổng tiền thanh toán/Grant Total:
                        .sub-item-body
                      %td{:align => "right", :style => "border:1px solid #000;border-left:0px;"}
                        %span{:style => "font-size:14px;font-weight:bold;"}
                          = number_with_delimiter @order.final_total
          / %tr
          /   %td{colspan: "5", :align => "center"}
          /     %strong Tổng
          /   %td{:align => "right"}
          /     %strong
          /       = number_with_delimiter current_order.final_total.round
      %p
        %center
          %strong
            Cảm ơn Quý khách đã sử dụng dịch vụ tại Hoàng Châu Palace!

app/views/reports/report_product.html.haml
#printer.simple-layout-center
  #module_322
    .report-bound{:style => " page:land;"}
      %div{style: "text-align: center; margin: 20px 0 20px 0"}
        %strong
          = "BÁO CÁO DOANH THU THEO SẢN PHẨM"
      %table.table-bound{:border => "1", :bordercolor => "#CCCCCC", :cellpadding => "5", :cellspacing => "0", :style => "margin: 0 50px 0 50px", :width => "880px"}
        %tbody
          %tr{:bgcolor => "#EFEFEF", :valign => "middle"}
            %th{:align => "center"} STT
            %th.report_table_header{:align => "center"} Tên sản phẩm
            %th.report_table_header{:align => "center"} Số lượng đã bán
            %th.report_table_header{:align => "center"} Giá
            %th.report_table_header{:align => "center"} Tổng
          - total = 0
          - @products.each do |t|
            %tr
              %td.report_table_column{:align => "center", :nowrap => ""}= t.id
              %td.report_table_column{:align => "left", :nowrap => ""}= t.name
              %td.report_table_column{:align => "right", :nowrap => ""}
                - if t.id == 36 || t.id == 37
                  - a = (t.stock_sold * 60).divmod(60)[0]
                  - b = (t.stock_sold * 60).divmod(60)[1].round
                  = "#{a}:#{b}"
                - else
                  = t.stock_sold
              %td.report_table_column{:align => "right", :nowrap => ""}= number_with_delimiter t.price
              %td.report_table_column{:align => "right", :nowrap => ""}
                = number_with_delimiter (t.price.to_i * t.stock_sold).round(-3)
                - total = total + t.price.to_i * t.stock_sold
          %tr{:bgcolor => "white"}
            %td{:align => "center", :colspan => "4"}
              %strong Tổng
            %td.report_table_column{:align => "right", :nowrap => ""}
              %strong
                = number_with_delimiter total.round

app/views/reports/report_revenue.html.haml
%script{:src => "/assets/jquery-1.10.2.js", :type => "text/javascript"}
%script{:src => "/assets/jquery-ui.js", :type => "text/javascript"}
:javascript
  $(function() {
    $(".datepicker").datepicker({ dateFormat: "dd-mm-yy" }).val()
  });
#printer.simple-layout-center
  #module_322
    .report-bound{:style => " page:land;"}
      %table{:cellpadding => "10", :cellspacing => "0", :width => "100%"}
        %tbody
          %tr
            %td{:align => "center"}
              %font.report_title CHỌN NGÀY
              %br/
              %table
                %tbody
                  %tr
                    %td Ngày tháng bắt đầu
                    %td
                    %td Ngày tháng kết thúc
                  = form_tag report_revenue_path, method: "get" do
                    %tr
                      %td
                        %input{:type => "text", class: "datepicker", name: "start_date", value: session[:start_date]}
                      %td Đến
                      %td
                        %input{:type => "text", class: "datepicker", name: "to_date", value: session[:to_date]}
                    %tr
                      %td
                      %td
                      %td
                        = submit_tag "Báo cáo doanh thu theo hóa đơn", name: "bill"
                    %tr{colspan: "3"}
                      %td
                      %td
                      %td
                        = submit_tag "Báo cáo doanh thu theo sản phẩm", name: "products"
      - if @orders.present?
        %div{style: "text-align:center"}
          %h3 
            %p BÁO CÁO DOANH THU
            %span Từ ngày 
            %span{style: "color:red"} #{session[:start_date]}
            %span đến ngày 
            %span{style: "color:red"} #{session[:to_date]}
        %br/
        %table.table-bound{:border => "1", :bordercolor => "#CCCCCC", :cellpadding => "5", :cellspacing => "0", :style => "margin: 0 50px 0 50px", :width => "880px"}
          %tbody
            %tr{:bgcolor => "#EFEFEF", :valign => "middle"}
              %th{:align => "center"} STT
              %th.report_table_header{:align => "center"} Xem chi tiết
              %th.report_table_header{:align => "center"} Ngày
              %th.report_table_header{:align => "center"} Bàn
              %th.report_table_header{:align => "center"} Người tạo
              %th.report_table_header{:align => "center"} Tổng tiền
              %th.report_table_header{:align => "center"} Delete
            - total = 0
            - @orders.each do |t|
              - table = Quanly.where(id: t.quanly_id).first
              - user = User.where(id: t.user_id).first
              %tr{:bgcolor => "white"}
                %td{:align => "center"}= t.id
                %td
                  = link_to "Xem chi tiết", report_bill_path(id: t.id), target: "_blank"
                %td.report_table_column{:align => "center", :nowrap => ""}= t.created_at.to_date
                %td.report_table_column{:align => "left", :nowrap => ""}= table.name
                %td.report_table_column{:align => "center", :nowrap => ""}= user.name
                %td.report_table_column{:align => "right", :nowrap => ""}
                  = number_with_delimiter(t.final_total)
                  - total = total + t.final_total.to_i
                %td.report_table_column{:align => "right", :nowrap => ""}
                  = link_to "Delete", delete_order_path(t.id)
            %tr{:bgcolor => "white"}
              %td{:align => "center", :colspan => "5"}
                %strong Tổng
              %td.report_table_column{:align => "right", :nowrap => ""}
                %strong
                  = number_with_delimiter total
      - elsif @products.present?
        %div{style: "text-align:center"}
          %h3 
            %p BÁO CÁO DOANH THU THEO SẢN PHẨM
            %span Từ ngày 
            %span{style: "color:red"} #{session[:start_date]}
            %span đến ngày 
            %span{style: "color:red"} #{session[:to_date]}
        %br/
        %table.table-bound{:border => "1", :bordercolor => "#CCCCCC", :cellpadding => "5", :cellspacing => "0", :style => "margin: 0 50px 0 50px", :width => "880px"}
          %tbody
            %tr{:bgcolor => "#EFEFEF", :valign => "middle"}
              %th{:align => "center"} STT
              %th.report_table_header{:align => "center"} Tên sản phẩm
              %th.report_table_header{:align => "center"} Số lượng đã bán
              %th.report_table_header{:align => "center"} Giá
              %th.report_table_header{:align => "center"} Tổng
            - total = 0
            - @products.each do |t|
              %tr
                %td.report_table_column{:align => "center", :nowrap => ""}= t.id
                %td.report_table_column{:align => "left", :nowrap => ""}= t.name
                %td.report_table_column{:align => "right", :nowrap => ""}
                  - if t.id == 36 || t.id == 37
                    - a = (t.stock_sold * 60).divmod(60)[0]
                    - b = (t.stock_sold * 60).divmod(60)[1].round
                    = "#{a} Tiếng #{b} Phút"
                  - else
                    = t.stock_sold
                %td.report_table_column{:align => "right", :nowrap => ""}= number_with_delimiter t.price
                %td.report_table_column{:align => "right", :nowrap => ""}
                  = number_with_delimiter (t.price.to_i * t.stock_sold).round(-3)
                  - total = total + t.price.to_i * t.stock_sold
            %tr{:bgcolor => "white"}
              %td{:align => "center", :colspan => "4"}
                %strong Tổng
              %td.report_table_column{:align => "right", :nowrap => ""}
                %strong
                  = number_with_delimiter total.round
      - elsif @nodata.present?
        %p{style: "text-align: center; color:red"}
          %strong "Không có dữ liệu!"

app/views/reports/reports_detail.html.haml
%li.menumain{:style => "float:right;list-style-type: none;"}
  %a{:onclick => "window.print();return false;", :title => "In"}
    %img{:height => "20", :src => "/assets/printer.png"}/
  %ul{:style => "display: none;"}
#printer.simple-layout-center
  #module_505
    :css
      / <!--//IF:cond($this->map['preview'])
      / @media print{body {display:none;}}
      / //IF:cond
      \-->
      .restaurant-invoice-bound{
        float:left;
        width:400px;
        padding:5px;
      }
      #product_detail{
        border:1px solid #E5E6E7; 
      }
      #product_detail tr{
        border:1px solid #E5E6E7; 
      }
      #product_detail tr td{
        border:1px solid #E5E6E7; 
      }
      #product_detail tr th{
        border:1px solid #E5E6E7; 
      }
    %div{:style => "width:700px;text-align:center; margin:auto !important; border:1px solid silver; padding:5px;"}
      .restaurant-invoice-bound
        .item-body
          %table{:cellpadding => "0", :cellspacing => "0", :style => "margin-bottom:10px;", :width => "100%"}
            %tbody
              %tr
                %td{:width => "1%"}
                  %img{:src => "/assets/hoa_don.png", :width => "80px;"}/
                %td{:style => " text-align:left; padding-left:50px;"}
                  %span HOÀNG CHÂU PALACE
                  %br/
                  %span Địa chỉ: Tuần B - Quỳnh Châu - Quỳnh Lưu - Nghệ An
                  %br/
                  %span Điện thoại: 0967 938 998
                  %br/
              %tr
                %td
                %td{:style => " text-align:center;"}
                  %span{:style => "font-size:18px;font-weight:bold;"} HÓA ĐƠN THANH TOÁN
                  %br/
                  %span{:style => "font-size:11px;"} Ngày 01 Tháng 12 Năm 2014
                  %br/
          %table{:cellpadding => "0", :cellspacing => "0", :style => "width: 100%; margin: 10px auto;"}
            %tbody
              %tr
                %td{:style => "text-align: left; font-size: 11px;"} Số hóa đơn: LP-011214-3
                %td{:style => "text-align: right; font-size: 11px;"} Thu ngân/Cashier: Tamxinh
              %tr
                %td{:style => "text-align: left; font-size: 11px;"} Agent/Khách hàng: Mang về
                %td{:style => "text-align: right; font-size: 11px;"} Ngày in: 01/12/2014 14:58'
              %tr
                %td{:style => "text-align: left; font-size: 11px;"} Bàn/Table No: Bàn 01 (SL Người: 1) &nbsp;
        .item-body
        %br/
        %div{:style => "border-bottom:1px solid #E5E6E7"}
        %table#product_detail{:border => "0", :bordercolor => "#000000", :cellspacing => "0", :width => "100%"}
          %tbody
            %tr
              %th{:align => "left", :width => "1%"}
                STT
              %th{:align => "left", :style => "padding-left:10px;", :width => "50%"}
                Diễn giải
              %th{:align => "center", :width => "10%"}
                Đơn vị
              %th{:align => "center", :width => "8%"}
                Yêu cầu
              %th{:align => "center", :width => "8%"}
                SD
              %th{:align => "center", :width => "10%"}
                Đơn giá
              %th{:align => "center", :nowrap => "nowrap", :width => "20%"}
                Thành tiền
            - i = 1
            - @bills.each do |t|
              - @product = Product.where(id: t.product_id).first
              %tr{:valign => "top"}
                %td
                  = i
                  - i = i + 1
                %td{:align => "left"}
                  = @product.name
                  .item-body
                %td{:align => "center"}
                  = @product.unit
                %td{:align => "center"}
                  = t.quantity
                %td{:align => "center"}
                  = t.quantity
                %td{:align => "right"}
                  = number_with_delimiter @product.price
                %td{:align => "right"}
                  = number_with_delimiter t.total_price
        %div{:style => "border-bottom:1px solid #E5E6E7"}
        .item-body.total-group
          .item-body &nbsp;
          %table{:border => "0", :cellpadding => "2", :cellspacing => "0", :width => "100%"}
            %tbody
              %tr
                %td{:align => "right"}
                  %table{:border => "0", :cellpadding => "2", :width => "350"}
                    %tbody
                      %tr
                        %td{:width => "80%"}
                          %strong Thành tiền/Amount:
                          .sub-item-body
                        %td{:align => "right", :width => "20%"} 40,000
                      %tr
                        %td
                          %strong Giảm giá/Order Discount:
                          .sub-item-body
                        %td{:align => "right"} - 0
                      %tr
                        %td
                          %strong Tổng sau giảm giá:
                          .sub-item-body
                        %td{:align => "right"} 40,000
                      %tr
                        %td
                          %strong (10%) Thuế/Tax:
                          .sub-item-body
                        %td{:align => "right"} + 4,000
                      %tr
                        %td
                          %strong Tổng bao gồm thuế:
                          .sub-item-body
                        %td{:align => "right"} 44,000
                      %tr
                        %td{:align => "left", :nowrap => "nowrap", :style => "border:1px solid #000;border-right:0px;"}
                          %strong Tổng tiền thanh toán/Grant Total:
                          .sub-item-body
                        %td{:align => "right", :style => "border:1px solid #000;border-left:0px;"}
                          %span{:style => "font-size:14px;font-weight:bold;"}
                            = number_with_delimiter @order.total_price
                  %div
                    %span
                      %i
                        (*) Quý khách vui lòng lấy hóa đơn GTGT trong tháng.
                        = succeed "C\u{1ea3}m" do
                          %br/
                        ơn Quý khách đã sử dụng dịch vụ tại Hoang Chau Palace!
                  %div{:style => "color:#F00;font-weight:bold;padding-top:10px;font-size:16px;"}